name: sport2
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0
  cupertino_icons: ^1.0.2
  shared_preferences: ^2.1.0
  provider: ^6.0.5
  riverpod: ^2.3.6
  flutter_riverpod: ^2.3.6
  dio: ^5.1.1
  animated_text_kit: ^4.2.2
  firebase_crashlytics: ^3.1.2
  hive_flutter: ^1.1.0
  flutter_launcher_icons: ^0.13.1
  sidebarx: ^0.15.0
  json_annotation: ^4.8.0


dev_dependencies:
  build_runner: ^2.3.3
  freezed: ^2.2.1
  freezed_annotation: ^2.2.0
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  json_serializable: ^6.6.1


flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/icon.png"
  min_sdk_android: 21
  web:
    generate: true
    image_path: "assets/icons/icon.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path:  "assets/icons/icon.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/icons/icon.png"

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/

  fonts:
   - family: JetBrainsMono
     fonts:
       - asset: fonts/JetBrainsMono-Regular.ttf
       - asset: fonts/JetBrainsMono-Bold.ttf
         weight: 700
