# Generated by Django 4.2 on 2023-04-27 12:47

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SiteUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(blank=True, max_length=63, verbose_name="Имя"),
                ),
                (
                    "surname",
                    models.CharField(blank=True, max_length=63, verbose_name="Фамилия"),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=63, verbose_name="Отчество"
                    ),
                ),
                (
                    "competence",
                    models.CharField(
                        blank=True,
                        choices=[("BACK", "Backend"), ("FRON", "Frontend")],
                        default="BACK",
                        max_length=4,
                        verbose_name="Компетенция",
                    ),
                ),
                (
                    "rating",
                    models.IntegerField(blank=True, null=True, verbose_name="Рейтинг"),
                ),
                (
                    "awards",
                    models.TextField(blank=True, null=True, verbose_name="Достижения"),
                ),
                (
                    "skills",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=django.contrib.postgres.fields.ArrayField(
                            base_field=models.CharField(blank=True), size=None
                        ),
                        blank=True,
                        null=True,
                        size=None,
                        verbose_name="Навыки",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("SP", "Спортсмен"),
                            ("RE", "Представитель региональной федерации"),
                            ("AD", "Администратор ФСП"),
                            ("PA", "Партнер федерации"),
                        ],
                        default="SP",
                        max_length=2,
                        verbose_name="Роль",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Пользователь",
                "verbose_name_plural": "Пользователи",
            },
        ),
    ]
